"""Delete Data

Revision ID: 4133e1211733
Revises: b02416ade835
Create Date: 2025-01-30 14:04:25.830232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4133e1211733'
down_revision = 'b02416ade835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
